### ISSUE TITLE
*** Error in `kcapi': double free or corruption (out): 0x77529448 ***

### ISSUE THREAD

**Issue by malaterre** [smuellerDD/libkcapi#13]
I can reproduce a simple segfault on my Creator CI20 (kernel 4.9.20).

```
ci20@ci20:~/libkcapi-0.13.0/test$ gdb ./kcapi
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "mipsel-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./kcapi...done.
8a53171b4 -a fb7bc304a3909e66e2e0c5ef952712dd884ce3e7324171369f2c5db1adc48c7d5ba
Starting program: /home/ci20/libkcapi-0.13.0/test/kcapi -v -d 4 -x 2
-c "ccm(aes)" -q
4edb58e8d5eb6bc711c43a6f3693daebde2e5524f1b55297abb29f003236e43d -t
a7877c99 -n 674742abd0f5ba -k 2861fd0253705d7875c95ba8a53171b4 -a
fb7bc304a3909e66e2e0c5ef952712dd884ce3e7324171369f2c5db1adc48c7d
Failed to read a valid object file image from memory.
libkcapi - Error: AF_ALG: bind failed (errno: 2)
Allocation of cipher failed

Program received signal SIGSEGV, Segmentation fault.
_kcapi_handle_destroy (handle=0x12) at ../lib/kcapi-kernel-if.c:783
783 if (handle->tfmfd != -1)
(gdb) bt full
#0  _kcapi_handle_destroy (handle=0x12) at ../lib/kcapi-kernel-if.c:783
No locals.
#1  0x00405edc in cavs_aead (cavs_test=0x7fffe968, loops=4, splice=1)
    at kcapi-main.c:945
        handle = 0x12
        outbuf = 0x0
        outbuflen = <optimized out>
        inbuf = 0x0
        inbuflen = <optimized out>
        fullbuflen = <optimized out>
        ret = -22
        newiv = 0x0
        newivlen = 0
        errsv = 0
        i = 0
        assoc = 0x0
        data = 0x0
        tag = 0x0
        assoclen = 0
        datalen = 0
        taglen = 0
        i_assoc = 0x0
        i_data = 0x0
---Type <return> to continue, or q <return> to quit---
        i_tag = 0x0
        i_assoclen = 0
        i_datalen = 0
        i_taglen = 0
        begin = {tv_sec = 2147477720, tv_nsec = 4456448}
        end = {tv_sec = 2012267316, tv_nsec = 4481392}
        total = 0
#2  0x004032e4 in main (argc=18, argv=0x7fffec44) at kcapi-main.c:2271
        c = <optimized out>
        ret = <optimized out>
        rc = 1
        stream = 0
        large = 0
        loops = 4
        splice = <optimized out>
        cavs_test = {cipher = "ccm(aes)", '\000' <repeats 54 times>,
          aligned = 0, timing = 0, enc = 0, type = 2, pt = 0x0, ptlen = 0,
          ct = 0x43f008
"N\333X\350\325\353k\307\021\304:o6\223\332\353\336.U$\361\265R\227\253\262\237",
ctlen = 32,
          iv = 0x43f050 "\agGB\253\320", <incomplete sequence \365\272>,
          ivlen = 16, key = 0x43f090 "(a\375\002Sp]xu\311[\250\245\061q\264",
          keylen = 16, pubkey = 0x0, pubkeylen = 0,
          assoc = 0x43f068
"\373{\303\004\243\220\236f\342\340\305\357\225'\022�---Type <return>
to continue, or q <return> to quit---
�L\343\347\062Aq6\237,]\261\255Č}", assoclen = 32,
          tag = 0x43f030 "\247\207|\231", taglen = 4, outlen = 0}
(gdb) quit

```

During a debug session I see that the function `_kcapi_handle_destroy` is called twice on the same handle in this case. It may make sense to sanitize the value of handle to NULL so that next call is aware.

Debug session:

```
(gdb) 
libkcapi - Error: AF_ALG: bind failed (errno: 2)
983                     goto err;
(gdb) 
1012            _kcapi_handle_destroy(handle);
(gdb) p handle
$8 = (struct kcapi_handle *) 0x43f0a8
(gdb) n
1014    }
(gdb) 
cavs_aead (cavs_test=0x7fffe968, loops=4, splice=1) at kcapi-main.c:806
806                     printf("Allocation of cipher failed\n");
(gdb) 
Allocation of cipher failed
804             ret = -EINVAL;
(gdb) 
104       return __printf_chk (__USE_FORTIFY_LEVEL - 1, __fmt, __va_arg_pack ());
(gdb) 
945             kcapi_aead_destroy(handle);
(gdb) s
kcapi_aead_destroy (handle=0x12) at ../lib/kcapi-aead.c:34
34              _kcapi_handle_destroy(handle);
(gdb) c
Continuing.

Program received signal SIGSEGV, Segmentation fault.
_kcapi_handle_destroy (handle=0x12) at ../lib/kcapi-kernel-if.c:783
783             if (handle->tfmfd != -1)

```

**Comment by smuellerDD** [comment]
Thank you for your bug report, but this has been closed with patch 663e0b77.

To ensure safe programming, I now have also initialized the pointer to NULL which catches this issue too.

In addition, I added some code cleanups in the allocation error code path in other functions which exhibit the same issue.
